<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AsyncResponse.ServiceDefaults\AsyncResponse.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\src\AsyncResponse.Core\AsyncResponse.Core.csproj" />
    <ProjectReference Include="..\..\src\AsyncResponse.Channels.NATS\AsyncResponse.Channels.NATS.csproj" />
    <ProjectReference Include="..\..\src\AsyncResponse.Channels.PostgreSQL\AsyncResponse.Channels.PostgreSQL.csproj" />
    <ProjectReference Include="..\..\src\AsyncResponse.Channels.Redis\AsyncResponse.Channels.Redis.csproj" />
    <ProjectReference Include="..\..\src\AsyncResponse.Channels.SqlServer\AsyncResponse.Channels.SqlServer.csproj" />
    <ProjectReference Include="..\..\src\AsyncResponse.Transports.AzureServiceBus\AsyncResponse.Transports.AzureServiceBus.csproj" />
    <ProjectReference Include="..\..\src\AsyncResponse.Transports.GooglePubSub\AsyncResponse.Transports.GooglePubSub.csproj" />
    <ProjectReference Include="..\..\src\AsyncResponse.Transports.Kafka\AsyncResponse.Transports.Kafka.csproj" />
    <ProjectReference Include="..\..\src\AsyncResponse.Transports.NATS\AsyncResponse.Transports.NATS.csproj" />
    <ProjectReference Include="..\..\src\AsyncResponse.Transports.PostgreSQL\AsyncResponse.Transports.PostgreSQL.csproj" />
    <ProjectReference Include="..\..\src\AsyncResponse.Transports.RabbitMQ\AsyncResponse.Transports.RabbitMQ.csproj" />
    <ProjectReference Include="..\..\src\AsyncResponse.Transports.Redis\AsyncResponse.Transports.Redis.csproj" />
    <ProjectReference Include="..\..\src\AsyncResponse.Transports.SqlServer\AsyncResponse.Transports.SqlServer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\src\AsyncResponse.Core\Logging\AsyncResponseLoggerExtensions.cs" Link="Logging\AsyncResponseLoggerExtensions.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
  </ItemGroup>

</Project>
