<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="13.4.4" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>asyncresponse-integrationtests-apphost-5ff760b0-7ffb-4cd9-8fe5-6464f1286486</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="13.4.4" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.4.4" />
    <PackageReference Include="MessagePack" Version="3.1.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\samples\AsyncResponse.Sample\AsyncResponse.Sample.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="servicebus-emulator-config.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <Target Name="BuildAspireProjectResourceDebugOutput" BeforeTargets="Build">
    <MSBuild
      Projects="..\..\samples\AsyncResponse.Sample\AsyncResponse.Sample.csproj"
      Targets="Build"
      Properties="Configuration=Debug;TargetFramework=net10.0" />
  </Target>

</Project>
